---
title: Burgrfck
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: fredbobathon@gmail.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Burgrfck
email: fredbobathon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Your burger fucking awaits you.
baseurl: "" # the subpath of your site, e.g. /blog
layout: default
comments: true
url: "http://burgrfck.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: burgrfck
github_username:  fredbobathon
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
---
