---
title: Burgrfck
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: fredbobathon@gmail.com
description: 'Your burger fucking awaits you.

'
baseurl: ''
layout: default
comments: true
url: http://burgrfck.com
twitter_username: burgrfck
github_username: fredbobathon
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
